// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    'Bi:arrowUp': typeof import('~icons/bi/arrow-up')['default']
    'Charm:eye': typeof import('~icons/charm/eye')['default']
    'Cil:drop': typeof import('~icons/cil/drop')['default']
    CityPreview: typeof import('./components/CityPreview.vue')['default']
    CitySuggestion: typeof import('./components/CitySuggestion.vue')['default']
    'IconParkTwotone:speed': typeof import('~icons/icon-park-twotone/speed')['default']
    MainLayout: typeof import('./components/MainLayout.vue')['default']
    'Mdi:cog': typeof import('~icons/mdi/cog')['default']
    'Mdi:magnify': typeof import('~icons/mdi/magnify')['default']
    'Mdi:trashCanOutline': typeof import('~icons/mdi/trash-can-outline')['default']
    NewCityForm: typeof import('./components/NewCityForm.vue')['default']
    'Prime:bars': typeof import('~icons/prime/bars')['default']
    SettingsLayout: typeof import('./components/SettingsLayout.vue')['default']
    Spinner: typeof import('./components/Spinner.vue')['default']
    WeatherView: typeof import('./components/WeatherView.vue')['default']
    WeatherWidget: typeof import('./components/WeatherWidget.vue')['default']
  }
}
