// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    CityPreview: typeof import('./components/CityPreview.vue')['default']
    HelloWorld: typeof import('./components/HelloWorld.vue')['default']
    MainLayout: typeof import('./components/MainLayout.vue')['default']
    NewCityForm: typeof import('./components/NewCityForm.vue')['default']
    PiButton: typeof import('primevue/button')['default']
    SettingsLayout: typeof import('./components/SettingsLayout.vue')['default']
    WeatherView: typeof import('./components/WeatherView.vue')['default']
    WeatherWidget: typeof import('./components/WeatherWidget.vue')['default']
  }
}
